### ISSUE TITLE
💡 Would have sense to have file content in real files instead of strings?

### ISSUE THREAD

**Issue by oscard0m** [octoherd/create-octoherd-script#11]
An idea came to my mind from this PR: https://github.com/octoherd/create-octoherd-script/pull/10/files

What if we have had [this GitHub workflow](https://github.com/octoherd/create-octoherd-script/blob/8576bd8e47428ec4ca640aa502062c90fd611b38/lib/create-test-action.js#L4-L44) as a file and checked periodically by renovate? An automatic PR would have updated it for us (and for future releases of actions we decide to us in workflows).

Checking other files we scaffold with https://github.com/octoherd/create-octoherd-script maybe some checks and logic could be applied:
- Prettier / Lint
- Unit tests / transpilation / compilation...
- Easier to manipulate with octoherd actions (modify its content in a programmatic way maybe?)
- It would open the door of scaffolding a package.json and package.lock with controlled version of packages (controlled by [renovate](https://github.com/octoherd/cli/issues/15)) instead of doing an `npm i` (not sure if this is valuable or it complicates more the ecosystem)

What's your opinion here @gr2m

**Comment by gr2m** [comment]
> What if we have had [this GitHub workflow](https://github.com/octoherd/create-octoherd-script/blob/8576bd8e47428ec4ca640aa502062c90fd611b38/lib/create-test-action.js#L4-L44) as a file and checked periodically by renovate? An automatic PR would have updated it for us (and for future releases of actions we decide to us in workflows).

That's a good idea, I think we can do that.

> Checking other files we scaffold with https://github.com/octoherd/create-octoherd-script maybe some checks and logic could be applied:

I don't want to force too much setup on people, they have their own preferences. Right now I think we should should probably sit back and see what people using it say about it
