### ISSUE TITLE
💡 To add `// @ts-check`

### ISSUE THREAD

**Issue by oscard0m** [octoherd/create-octoherd-script#13]
Working in local was not giving to me JS errors by default. I was missing `checkJS` setting in my VSCode. After enabling it, I got this error:

![image](https://user-images.githubusercontent.com/2574275/110244102-7bc31280-7f5d-11eb-8e69-2b1bf443734f.png)

this `jsconfig.json` fixed the error for me:

```
{
    "compilerOptions": {
        "checkJs": true,
        "module": "es2020",
        "target": "es2020",
    }
}
```

**Comment by gr2m** [comment]
can we just add a `// @ts-check` to the `script.js` file for now?

**Comment by oscard0m** [comment]
> can we just add a `// @ts-check` to the `script.js` file for now? Will it have the same effect?

Let me give it a try

**Comment by oscard0m** [comment]
Modified title. I would go for the `//ts-check` solution
