### ISSUE TITLE
💡 scaffold `.vscode/settings.json` with `checkJS` enabled when creating repository

### ISSUE THREAD

**Issue by oscard0m** [octoherd/create-octoherd-script#15]
`.vscode/settings.json`

```
{
  "js/ts.implicitProjectConfig.checkJs": true
}
```

Do you think it could be intereting for users? Maybe making it optional under a `prompt({type: "confirm"})`?

**Comment by gr2m** [comment]
How about we add 

```js
// @ts-check
```

to the first line of the `script.js` file? That will make it work for all editors that support it?

I also wonder if we should run the `tsc --checkJs` check with `npx` on CI, as part of the "test" step in `test.yml`? What do you think?

**Comment by oscard0m** [comment]
> How about we add
> 
> ```js
> // @ts-check
> ```
> 
> to the first line of the `script.js` file ([docs](https://www.typescriptlang.org/docs/handbook/intro-to-js-ts.html#ts-check))? That will make it work for all editors that support it?

I can give it a try but... this would leave responsibility to developers adding on each js file they create this comment and, with `settings.json` would be for every `.js` file by default right?

**Comment by gr2m** [comment]
> I can give it a try but... this would leave responsibility to developers adding on each js file they create this comment and, with `settings.json` would be for every `.js` file by default right?

yes, but that way we don't force yet another file on people, and they can enable / disable it as they like. Also not everyone is using VS Code, I don't want to add editor-specific settings. The alternative would be to add `jsconfig.json`, but I think I would prefer to just adding the `// @ts-check` for now. I think most scripts will be a single file anyway

**Comment by oscard0m** [comment]
Yes, you are right:
`settings.json` would be Specific to VS Code and we don't want to be close to it so in case we need to scaffold a configuration, would be better to be [`.editorconfig`](https://editorconfig.org/) (if they support the js check part) or `jsconfig.json`

---

Tried in `script-renovate-setup` and it works fine to me so... I would say to go for this solution for the moment.

**Comment by oscard0m** [comment]
If you like the solution, I would create an Octoherd script to add `//ts-check` to `script.js` for already existing files in the org

![image](https://user-images.githubusercontent.com/2574275/110257532-a4b7c780-7f9e-11eb-805c-492632f416e6.png)

**Comment by gr2m** [comment]
Yes, let's add it to the `npm init octoherd-script` and create an @octoherd script that will add it to existing scripts that do not have it yet

**Comment by oscard0m** [comment]
> Yes, let's add it to the `npm init octoherd-script` and create an @octoherd script that will add it to existing scripts that do not have it yet

Already scaffolded in https://github.com/octoherd/create-octoherd-script/pull/17
I would wait for a need to scaffold it for existing ones. When it really becomes a problem.
