### ISSUE TITLE
if script option is boolean, mentiond both "--option-name" and "--no-option-name" in options table

### ISSUE THREAD

**Issue by gr2m** [octoherd/create-octoherd-script#20]
follow up to https://github.com/octoherd/octoherd/discussions/18#discussioncomment-481289

So instead of 

| option           | type    | description         |
| ---------------- | ------- | ------------------- |
| `--squash-merge` | boolean | toggle squash merge |
| `--merge-commit` | boolean | toggle merge commit |
| `--rebase-merge` | boolean | toggle rebase merge |

the script would create

| option                                  | type    | description         |
| --------------------------------------- | ------- | ------------------- |
| `--squash-merge` or `--no-squash-merge` | boolean | toggle squash merge |
| `--merge-commit` or `--no-merge-commit` | boolean | toggle merge commit |
| `--rebase-merge` or `--no-rebase-merge` | boolean | toggle rebase merge |

would that work for you @MunifTanjim?

**Comment by MunifTanjim** [comment]
I didn't think of documenting it this way. This would be great! 😃
