### ISSUE TITLE
Clarify "email for Code of Conduct" question

### ISSUE THREAD

**Issue by gr2m** [octoherd/create-octoherd-script#28]
I've seen @bdougie being confused by this question during his stream on Friday:
https://www.twitch.tv/videos/989570564

We should clarify that the email is for the `CODE_OF_CONDUCT.md` file of the newly created repository, and not something @octoherd asks to get from its users for some reason

The change needs to happen in `lib/prompts.js`.

**Comment by gr2m** [comment]
instead of the current question:

> ? Email for Code of Conduct

We could do

> ? Email for the repository's CODE_OF_CONDUCT.md file

Would that make it clear? @bdougie

**Comment by bdougie** [comment]
Yeah, that would be helpful. It is much more specific that its is for the soon-to-be-generated file. Though, It might be more clear as:

> What email can folks reach out to for Code of Conduct inquiries?

**Comment by gr2m** [comment]
> What email can folks reach out to for Code of Conduct inquiries?

love it, let's use that, thank you!
